project:
  type: website
  output-dir: docs

website:
  title: "PORTFOLIO"
  navbar:
    left:
      - index.qmd
      - contact.qmd
      - Projects.qmd
      - SourceCode.qmd
      

format:
  html:
    theme: minty
    css: styles.css
    toc: true

editor: visual

